version: "3"
# 每一个容器称为一个服务
services:
  node-app: 
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONG_USER=bode
      - MONGO_PASSWORD=bode
    command: npm run dev  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bode
      - MONGO_INITDB_ROOT_PASSWORD=bode